version: '3'
services:
  app:
    container_name: dac-cinema-api
    build: .
    volumes:
      - ./:/go/src/app
    ports:
      - '8080:8080'
    environment:
      CONFIG_PATH: ./configuration.toml
      # CONFIG_PATH: ${CONFIG_PATH:-default}
